version: "3.9"

services:
  comfyui:
    user: "1000:1000"
    build: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "8888:8188"
    volumes:
      - "./models:/workspace/ComfyUI/models"
      - "./input:/workspace/ComfyUI/input"
      - "./temp:/workspace/ComfyUI/output/temp"
      - "./output:/workspace/ComfyUI/output"